In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
import statsmodels.formula.api as sm

In [2]:
data = pd.read_csv("Startups.csv")

In [3]:
data.head(10)

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94
5  131876.90        99814.71        362861.36    New York  156991.12
6  134615.46       147198.87        127716.82  California  156122.51
7  130298.13       145530.06        323876.68     Florida  155752.60
8  120542.52       148718.95        311613.29    New York  152211.77
9  123334.88       108679.17        304981.62  California  149759.96

In [4]:
real_X = data.iloc[:,0:4].values
real_Y = data.iloc[:,4].values

In [5]:
le = LabelEncoder()
real_X[:,3] = le.fit_transform(real_X[:,3])
oneHE = OneHotEncoder()
real_X = oneHE.fit_transform(real_X).toarray() #iam getting error since here transform should be for 3 categories only.
real_X

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [1., 0., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 1., 0., 0.]])

In [6]:
real_X = real_X[:,1:] # for eleminating dummy variables d-1 variables are taken.

In [8]:
train_X ,test_X, train_Y, test_Y = train_test_split(real_X, real_Y, train_size=0.7, random_state=0)

In [9]:
mlr = LinearRegression()
mlr.fit(train_X,train_Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [12]:
pred_y = mlr.predict(test_X)
pred_y # getting worng values due to error in onehotencoding check once

array([111145.20387789, 100011.09115512, 111145.20387789, 111145.20387789,
       111145.20387789, 121484.45374587, 121484.45374587, 121484.45374587,
       111145.20387789, 111145.20387789, 111145.20387789, 121484.45374587,
       111145.20387789, 100011.09115512, 111145.20387789])

In [13]:
test_Y

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94,  96778.92,  96479.51,
       105733.54,  96712.8 , 124266.9 ])

In [15]:
mlr.coef_ # this is wrong check

array([-2.62870752e+04, -1.88527912e+04, -2.05514846e+04, -1.72418246e+04,
       -8.18545232e-12, -1.16035871e+04, -9.50420039e+03, -5.45696821e-12,
       -6.81233796e+03, -7.25706039e+03, -6.33511039e+03, -3.35398372e+03,
        1.45519152e-11,  2.91038305e-11,  4.45652404e-11,  3.63797881e-12,
       -3.73587129e+03, -8.61083718e+02,  2.46441628e+03, -6.82660458e+03,
       -8.18545232e-12, -8.03737959e+02, -1.81898940e-12,  7.27595761e-12,
        9.09494702e-12,  6.15431295e+03, -4.31080458e+03,  8.99394628e+03,
       -3.39047792e+03,  1.72646498e+04, -7.27595761e-11,  1.14320863e+04,
        1.01467720e+04,  1.29530542e+03,  0.00000000e+00,  0.00000000e+00,
        2.81086208e+03,  7.15248204e+03,  1.02424388e+04,  1.65829563e+04,
        1.48691320e+04,  1.18355554e+04,  1.87038063e+04,  0.00000000e+00,
        2.04725121e+04,  0.00000000e+00,  3.05936563e+04,  2.35924588e+04,
       -3.35398372e+03, -2.62870752e+04,  0.00000000e+00, -6.33511039e+03,
        0.00000000e+00,  

In [16]:
mlr.intercept_

110880.24959295928

In [18]:
y =b0x0 + b1x1 + b2x2 + .... + bnxn # if x0 =1 then b0x0 = b0 so a column should be of unit values

In [20]:
real_X = np.append(arr = np.ones((50,1)).astype(int),values = real_X , axis =1)

In [23]:
real_X[:,0]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
x_opt = real_X[:,[0,1,2,3,4,5]]

In [2]:
reg_OLS = sm.OLS(endog =real_Y ,exog = x_opt).fit() # getting error

In [1]:
reg_OLS.summary()

In [ ]:
# remove P>|t| of 0.05 remove that x and fit again we got x2 = 0.99
x_opt = real_X[:,[0,1,3,4,5]]
reg_OLS = sm.OLS(endog =real_Y ,exog = x_opt).fit()
reg_OLS.summary() 
# continue this till P is <|